name: GBCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: gbo

    steps:
      - name: Disable SSL verification (temporary)
        run: git config --global http.sslVerify false

      - uses: actions/checkout@v4

      - name: Install Rust
        uses: msrd0/rust-toolchain@v1
        with:
          toolchain: stable
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android

      - name: Setup Android SDK
        run: |
          export ANDROID_HOME=/opt/android-sdk
          export NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Android APK
        run: |
          export ANDROID_HOME=/opt/android-sdk
          export NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
          cargo tauri android build --apk

      - name: Deploy APK
        run: |
          sudo mkdir -p /opt/gbo/releases/botapp
          sudo cp ./target/android/release/apk/*.apk /opt/gbo/releases/botapp/
          sudo chmod 644 /opt/gbo/releases/botapp/*.apk
